version: '3.8'
services:
  localstack:
    image: localstack/localstack:3.3.0 # Зафіксована версія (зміни на ту, з якою працюєш)
    container_name: integration_aws_test
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      # SERVICES видалено через підтримку lazy-loading
    healthcheck:
      # Перевіряємо загальну готовність LocalStack до прийому запитів
      test: ["CMD-SHELL", "curl -s http://localhost:4566/_localstack/init/ready | grep -q '\"completed\": true'"]
      interval: 5s
      timeout: 5s
      retries: 10